In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
training_dataset_path = './Dataset/TrainingData/'
testing_dataset_path = './Dataset/TestData/'
dataset_path = './Dataset/'

In [3]:
samplesub_df = pd.read_csv(dataset_path+"allzeroes_sample.csv")

In [4]:
print(samplesub_df.columns)

Index(['Outcome'], dtype='object')


In [5]:
outcome = []
outcome.append("Outcome")

In [6]:
dfx = pd.read_csv(training_dataset_path+"Diabetes_XTrain.csv")
dfx.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age'],
      dtype='object')

In [7]:
dfy = pd.read_csv(training_dataset_path+"Diabetes_YTrain.csv")

In [8]:
print(dfx.shape)
dfx.values

(576, 8)


array([[  7.   , 168.   ,  88.   , ...,  38.2  ,   0.787,  40.   ],
       [  8.   , 110.   ,  76.   , ...,  27.8  ,   0.237,  58.   ],
       [  7.   , 147.   ,  76.   , ...,  39.4  ,   0.257,  43.   ],
       ...,
       [  2.   , 122.   ,  60.   , ...,  29.8  ,   0.717,  22.   ],
       [  4.   , 154.   ,  72.   , ...,  31.3  ,   0.338,  37.   ],
       [  1.   ,  88.   ,  78.   , ...,  32.   ,   0.365,  29.   ]])

In [9]:
print(dfy.shape)
dfy.values

(576, 1)


array([[1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
    

In [10]:
X_train = dfx.values

In [11]:
Y_train = dfy.values

In [12]:
test_df = pd.read_csv(testing_dataset_path+"Diabetes_Xtest.csv")

In [13]:
X_test = test_df.values

In [14]:
def dist(x1,x2):
    return np.sqrt(sum((x1-x2)**2))
nearestpoints = 17
def knn(X,Y,test,k=nearestpoints):
    vals = []
    m = X.shape[0]
    
    for i in range(m):
        d = dist(test,X[i])
        vals.append((d,Y[i]))
        
    vals = sorted(vals)
    vals = vals[:k]
    vals = np.array(vals)
    
    new_vals = np.unique(vals[:,1],return_counts=True)
    index = new_vals[1].argmax()
    pred = new_vals[0][index]
    return(pred)

In [15]:
for i in range(X_test.shape[0]):
    pred = knn(X_train,Y_train,X_test[i])
    outcome.append(int(pred))

In [16]:
outcome = np.asarray(outcome)
df = pd.DataFrame(outcome)

In [17]:
df.to_csv(dataset_path+"submission"+str(nearestpoints)+".csv",index=False,header=0)

In [19]:
df = pd.read_csv(dataset_path+"submission17.csv")
df.shape

(192, 1)

In [20]:
df.values

array([[1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [21]:
df.columns

Index(['Outcome'], dtype='object')